version: '3'

vars:
  NODEJS_PROJECT: "github.com/pulumi/pulumi/sdk/v3/nodejs/cmd/pulumi-language-nodejs"
  NODE_MODULE_NAME: "@pulumi/pulumi"
  NODEJS_VERSION:
    sh: cd ../../ && pulumictl get version --language javascript && cd sdk/nodejs

tasks:
  ensure:
    cmds:
      - yarn install
    status:
      - yarn install --check-files

  lint:
    cmds:
      - ./node_modules/.bin/tslint -c tslint.json -p tsconfig.json

  build-package:
    cmds:
      - ./node_modules/.bin/tsc
      - cp tests/runtime/jsClosureCases_8.js bin/tests/runtime
      - cp tests/runtime/jsClosureCases_10_4.js bin/tests/runtime
      - cp -R tests/automation/data/. bin/tests/automation/data/
      - cp README.md ../../LICENSE package.json ./dist/* bin/
      - node ../../scripts/reversion.js bin/package.json {{.NODEJS_VERSION}}
      - node ../../scripts/reversion.js bin/version.js {{.NODEJS_VERSION}}
      - cp -R proto/. bin/proto/
      - mkdir -p bin/tests/runtime/langhost/cases/
      - find tests/runtime/langhost/cases/* -type d -exec cp -R {} bin/tests/runtime/langhost/cases/ \;

  build:
    deps: [build-package]
    cmds:
      - go build -o ../../bin/pulumi-language-nodejs -ldflags "-X github.com/pulumi/pulumi/sdk/v3/go/common/version.Version={{.NODEJS_VERSION}}" {{.NODEJS_PROJECT}}
    sources:
      - ./cmd/pulumi-language-nodejs/*.go
    generates:
      - ../../bin/pulumi-language-nodejs
    method: checksum

  install-plugin:
    cmds:
      - cp dist/pulumi-resource-pulumi-nodejs "{{.PULUMI_BIN}}"
      - cp dist/pulumi-analyzer-policy "{{.PULUMI_BIN}}"

  install-pkg:
    cmds:
      - mkdir -p "{{.PULUMI_NODE_MODULES}}/{{.NODE_MODULE_NAME}}"
      - cp -r bin/. "{{.PULUMI_NODE_MODULES}}/{{.NODE_MODULE_NAME}}"
      - cp yarn.lock "{{.PULUMI_NODE_MODULES}}/{{.NODE_MODULE_NAME}}"
      - rm -rf "{{.PULUMI_NODE_MODULES}}/{{.NODE_MODULE_NAME}}/node_modules"
      - cd "{{.PULUMI_NODE_MODULES}}/{{.NODE_MODULE_NAME}}" && yarn install --prefer-offline --production && (yarn unlink > /dev/null 2>&1 || true) && yarn link

  install:
    cmds:
      - task: build
      - task: install-plugin
      - task: install-pkg
      - GOBIN={{.PULUMI_BIN}} go install -ldflags "-X github.com/pulumi/pulumi/sdk/v3/go/common/version.Version={{.NODEJS_VERSION}}" {{.NODEJS_PROJECT}}
    sources:
      - ./cmd/pulumi-language-nodejs/*.go
    generates:
      - "{{.PULUMI_BIN}}/pulumi-language-nodejs"
    method: checksum

  yarn-test:
    cmds:
      - ./node_modules/.bin/istanbul test --print none _mocha -- --timeout 120000 'bin/tests/**/*.spec.js'
      - ./node_modules/.bin/istanbul report text-summary
      - ./node_modules/.bin/istanbul report text
      - ./node_modules/.bin/istanbul test --print none _mocha -- 'bin/tests_with_mocks/**/*.spec.js'
      - pushd tests/sxs_ts_3.6 && yarn ; tsc ; popd
      - pushd tests/sxs_ts_latest && yarn ; tsc ; popd

  test:
    cmds:
      - task: install
      - task: yarn-test
      - cmd: go test -count=1 -cover -timeout 1h -tags=all -parallel {{ .TESTPARALLELISM }} ./...
        ignore_error: true